name: Android Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: add keys
      env:
        KEYS: ${{ secrets.KEYS }}
      run: echo $KEYS > C:\Users\Pc Adrien\AndroidStudioProjects\Bootcamp\app\src\main\res\values\key.xml

    - name: Make gradlew executable
      run: chmod +x C:\Users\Pc Adrien\AndroidStudioProjects\Bootcamp\gradlew.bat

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
